title: <a href="https://www.github.com/Meateoreo">Andrew Wang</a> # your name (or website title) here
logo: "/images/linkedinPhoto.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Game Programmer and Designer</b>, Unity Developer that created Robopg and Stuffed. Seeking entry level programming or testing jobs.
  <br><br>
  Email: <i>aw6461@gmail.com</i>
  <br><br>
  <a href="https://meateor.itch.io">View My Games</a>
  <br><br>
  <a href="https://www.linkedin.com/in/andrewwanggp/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
